# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
dist: xenial
language: r
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm

addons:
  apt:
    packages:
      - libjq-dev

before_install:
  - nvm install 8
  - npm install netlify-cli -g
  - mkdir public

script:
  - Rscript -e 'blogdown::install_hugo(version = "0.55.6")'
  - Rscript -e 'blogdown::build_site(method = "html")'

after_success:
-  sh deploy.sh
